title: "Laboratório Solares - teste de construção do site"
email: "labSolares@gmail.com"
description: "Documentação do Laboratório Solares"
baseurl: "" # use "/" if your site is not in a subdirectory
url: "https://robertopcaldas.github.io/teste_labSolares" # your domain name
markdown: kramdown
theme: minima
