title: "Lab Solares"
email: "labSolares.UERJ@gmail.com"
description: "Documentação do Laboratório Solares"
baseurl: "" # use "/" if your site is not in a subdirectory
url: "https://github.com/LabSolares-UERJ/main" # your domain name
markdown: kramdown
theme: minima
